### ISSUE TITLE
Gradle option please

### ISSUE THREAD

**Issue by reflexdemon** [erosb/mvn-search#4]
Off late I am moving most of my projects to Gradle from Maven and will like to see if you can also produce Gradle dependency.

**Comment by SteKoe** [comment]
Addressed in #6. 🤞

**Comment by reflexdemon** [comment]
@SteKoe 
I liked your review. Thanks a ton. That will be useful.
I became a bit impatient and created https://github.com/reflexdemon/gradle-search and published it to npm

**Comment by reflexdemon** [comment]
In the sprit of #6 I am closing this issue now.
